name: Bug Report
description: Report a reproducible bug in Press
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Welcome to Agent issue tracker! Before creating an issue, please heed the following:

        1. This tracker should only be used to report bugs and request features / enhancements to Press Agent
            - For questions and general support, checkout the [user manual](https://docs.frappe.io/cloud/introduction) or use [forum](https://discuss.frappe.io/c/frappe-cloud/77)
        2. When making a bug report, make sure you provide all required information. The easier it is for
           maintainers to reproduce, the faster it'll be fixed.
        3. Search the existing issues to avoid creating duplicates.

  - type: textarea
    id: bug-info
    attributes:
      label: Information about bug
      description: Also tell us, what did you expect to happen?
      placeholder: Please provide as much information as possible.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output / Stack trace / Full Error Message.
      description: Please copy and paste any relevant log output. This will be automatically formatted.
      render: shell
